apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:      
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: renanrosa/nodejs-app:latest
        ports:
          - containerPort: 3000  
