apiVersion: v1
kind: Service
metadata:
  name: nodejs-app
  namespace: nodejs-app
  labels:
    app: nodejs-app
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 1337
  selector:
    app: nodejs-app